# Generated by Django 5.2.4 on 2025-07-25 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The legal name of the supplier.', max_length=255)),
                ('contact_person', models.CharField(blank=True, help_text='The primary contact person.', max_length=255, null=True)),
                ('email', models.EmailField(help_text="The supplier's primary email address.", max_length=254, unique=True)),
                ('phone', models.CharField(help_text="The supplier's 10-digit phone number (used for login).", max_length=10, unique=True)),
                ('address', models.TextField(blank=True, help_text='The physical address of the supplier.', null=True)),
                ('city', models.CharField(blank=True, help_text='The city where the supplier operates.', max_length=100, null=True)),
                ('cuisine', models.CharField(blank=True, choices=[('CHAAT', 'Chaat'), ('PAV_BHAJI', 'Pav Bhaji'), ('SOUTH_INDIAN', 'South Indian'), ('CHOLE_BHATURE', 'Chole Bhature'), ('MOMOS', 'Momos'), ('NORTH_INDIAN', 'North Indian'), ('ROLLS', 'Rolls'), ('BIRYANI', 'Biryani'), ('SWEETS', 'Sweets'), ('BEVERAGES', 'Beverages'), ('OTHER', 'Other')], help_text='The main cuisine or food category this supplier provides ingredients for.', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this supplier is active.')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Link to the user profile for this supplier.', on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
    ]
