# Generated by Django 5.2.4 on 2025-07-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cuisine', models.CharField(blank=True, choices=[('CHAAT', 'Chaat'), ('PAV_BHAJI', 'Pav Bhaji'), ('SOUTH_INDIAN', 'South Indian'), ('CHOLE_BHATURE', 'Chole Bhature'), ('MOMOS', 'Momos'), ('NORTH_INDIAN', 'North Indian'), ('ROLLS', 'Rolls'), ('BIRYANI', 'Biryani'), ('SWEETS', 'Sweets'), ('BEVERAGES', 'Beverages'), ('OTHER', 'Other')], max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
