# Generated by Django 5.2.4 on 2025-07-26 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("supplier", "0001_initial"),
        ("vendor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the product listing.", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A description for the product.",
                        null=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The price of the product.",
                        max_digits=10,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Stock Keeping Unit.", max_length=100, unique=True
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, help_text="Available stock quantity."
                    ),
                ),
                (
                    "cuisine",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CHAAT", "Chaat"),
                            ("PAV_BHAJI", "Pav Bhaji"),
                            ("SOUTH_INDIAN", "South Indian"),
                            ("CHOLE_BHATURE", "Chole Bhature"),
                            ("MOMOS", "Momos"),
                            ("NORTH_INDIAN", "North Indian"),
                            ("ROLLS", "Rolls"),
                            ("BIRYANI", "Biryani"),
                            ("SWEETS", "Sweets"),
                            ("BEVERAGES", "Beverages"),
                            ("OTHER", "Other"),
                        ],
                        help_text="The cuisine category for this product listing.",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this listing active and visible?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="The supplier for this product.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listings",
                        to="supplier.supplier",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        help_text="The vendor for this listing.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="vendor.vendor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Listing",
                "verbose_name_plural": "Product Listings",
                "ordering": ["-updated_at"],
                "unique_together": {("vendor", "sku")},
            },
        ),
    ]
