# Generated by Django 5.2.4 on 2025-07-26 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('supplier', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='vendor',
            field=models.ForeignKey(help_text='The vendor for this listing.', on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='vendor.vendor'),
        ),
        migrations.AlterUniqueTogether(
            name='productlisting',
            unique_together={('vendor', 'sku')},
        ),
    ]
