# Generated by Django 5.2.4 on 2025-07-27 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='supplier.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='productlisting',
            unique_together={('supplier', 'sku')},
        ),
    ]
