# Generated by Django 5.2.4 on 2025-07-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("vendor", "Vendor"),
                    ("supplier", "Supplier"),
                    ("buyer", "Buyer"),
                ],
                max_length=10,
            ),
        ),
    ]
